version: '3.8'

services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: gus
            MYSQL_PASSWORD: 123
            MYSQL_DATABASE: socialdb
        ports:
        - 3308:3308
        volumes:
        - ./data2:/docker-entrypoint-initdb.d

    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/var/www/redsocial-backend
        ports:
            - 7000:7000

        depends_on: 
            - db
        restart: on-failure
        
 